name: SKIventure
description: "SKIVENTURE – Khulafaur Rasyidin Learning App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Video Player (Local)
  video_player: ^2.8.3

  # YouTube Player
  youtube_player_flutter: ^9.0.1

  # Utility
  shared_preferences: ^2.3.0
  intl: ^0.19.0

  # Calendar
  table_calendar: ^3.1.2

  # WebView
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.0

  # Icons
  cupertino_icons: ^1.0.8

  # Animasi
  flutter_animate: ^4.5.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Package untuk generate ikon dipindah ke sini
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  # Hati-hati dengan override, pastikan memang diperlukan untuk kompatibilitas webview
  flutter_inappwebview: ^6.0.0

# Konfigurasi Ikon Aplikasi
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # Sesuaikan dengan minSdk di build.gradle

flutter:
  uses-material-design: true

  assets:
    - lib/videos/
    - assets/icon/ # Tambahkan folder icon ke assets agar terbaca